services:
  app:
    container_name: bs_task_app
    build:
      context: ./../
      dockerfile: ./docker/php8.2/dev/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=bsTaskApp"
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: bs_task_nginx
    build:
      context: ./php8.2/dev/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - app
