teams_list:
    path: /api/teams
    controller: App\Infrastructure\Controller\Team\TeamController::list
    methods: [GET]

team_details:
    path: /api/teams/{teamId}
    controller: App\Infrastructure\Controller\Team\TeamController::details
    methods: [GET]

create_team:
    path: /api/teams
    controller: App\Infrastructure\Controller\Team\TeamController::create
    methods: [POST]

update_team:
    path: /api/teams/{teamId}
    controller: App\Infrastructure\Controller\Team\TeamController::update
    methods: [PUT]

delete_team:
    path: /api/teams/{teamId}
    controller: App\Infrastructure\Controller\Team\TeamController::delete
    methods: [DELETE]

relocate_team:
    path: /api/teams/{teamId}/relocate
    controller: App\Infrastructure\Controller\Team\TeamController::relocate
    methods: [PUT]

list_players:
    path: /api/teams/{teamId}/players
    controller: App\Infrastructure\Controller\Player\PlayerController::list
    methods: [GET]

details_player:
    path: /api/teams/{teamId}/players/{playerId}
    controller: App\Infrastructure\Controller\Player\PlayerController::details
    methods: [GET]

add_player:
    path: /api/teams/{teamId}/players
    controller: App\Infrastructure\Controller\Player\PlayerController::add
    methods: [POST]

update_player:
    path: /api/teams/{teamId}/players/{playerId}
    controller: App\Infrastructure\Controller\Player\PlayerController::update
    methods: [PUT]

remove_player:
    path: /api/teams/{teamId}/players/{playerId}
    controller: App\Infrastructure\Controller\Player\PlayerController::remove
    methods: [DELETE]
