services:
  _defaults:
    autowire: true

  App\Tests\Resource\Fixtures\TeamFixtures:
    tags:
      - { name: 'doctrine.fixture.orm' }

  App\Shared\Infrastructure\Bus\CommandBus:
    public: true

  App\Shared\Infrastructure\Bus\QueryBus:
    public: true
